### PR TITLE
Add "Hide uncraftable" checkbox to UI

### PR DESCRIPTION
**Pull request by mtklass**
Hides uncraftable items from both item browser and search. Satisfies [Issue 22](https://github.com/twohoursonelife/twotech/issues/22)

### CODE REVIEW

**Comment by mtklass** [comment]
This assumes uncraftable to be a craftable depth of 0, unless it spawns naturally.

Some screenshots:

Show uncraftable browser:
Screenshot 2024-08-05 160708
Hide uncraftable browser:
Screenshot 2024-08-05 160714
Show uncraftable search:
Screenshot 2024-08-05 160750
Hide uncraftable search:
Screenshot 2024-08-05 160803

**Comment by mtklass** [comment]
I should note that I used Vue 2's eventBus, which is gone in Vue 3. It was by far the easiest way to make this work though; other methods fell short one way or another.

**Comment by connorhsm** [comment]
@mtklass if you could please rebase and resolve conflicts.

**Comment by mtklass** [comment]
On it -- testing rebased changes now.

**Comment by mtklass** [comment]
@connorhsm Ready to go!

**Review by connorhsm — APPROVED** [review]
Found and fixed one minor issue 😄 

Great addition, thank you!

**Pull request merged**
