### PR TITLE
Fully type out all data in processing code

### PR DESCRIPTION
**Pull request by mtklass**
This PR builds on top of https://github.com/twohoursonelife/twotech/pull/58.

PR 58 used mostly any's for values, but this branch builds on top of that branch, adding typing to everything.

The work is mostly done, with just the exported JSON files needing their types set.

We can either merge PR 58's changes and then take a look at this PR separately, or tackle this one directly.

I'll only mark these PRs as ready when they both are finished and still create a working twotech site (I've been checking incrementally as I go, so that shouldn't be a tall order).

### CODE REVIEW

**Comment by mtklass** [comment]
> > Try really hard _to_ spell relevant correctly
> 
> 😄
> 
> Lets tackle this one directly.

Totally meant to due that...

**Comment by mtklass** [comment]
Uh oh, I just realized the versions don't work for Objects, showing as unreleased...only problem I can find though.

**Comment by mtklass** [comment]
Alright, figured it out. The last challenge is turning on noImplicitAny, which I forgot to do before I declared things "done". Now I have to fix/add a few more types.

**Comment by mtklass** [comment]
Ok, **now** it's ready.

**Comment by mtklass** [comment]
Moved into draft because we found an issue with transparency during sprite generation.

It looks like it's some sort of issue with Canvas, but it's hard to tell why it isn't okay with what we're giving it.

**Comment by TanyaPegasus** [comment]
Is the issue like any of this? https://github.com/twohoursonelife/twotech/issues/43

**Comment by mtklass** [comment]
It's definitely related, at the very least. It might even be the same underlying issue. I'm doing an A/B with incremental changes to see what breaks/fixes things.

**Comment by mtklass** [comment]
Closed in favor of https://github.com/twohoursonelife/twotech/pull/61

**Pull request closed without merging**
