### PR TITLE
Web worker for search

### LINKED ISSUE #40: Debounce expensive search function
Debounce entire or partial search function. An improved search function was added in #38 which is invoked only if no other results would be returned, but causes the browser to freeze up after typing each character. Ideally, we should wait an appropriate time before calling the function repeatedly.

### PR DESCRIPTION
**Pull request by Eboubaker**
No more tab freezes!
Will fix #40 
The searching process has been moved to a web worker script, it will work in a separate thread.

### CODE REVIEW

**Comment by connorhsm** [comment]
@Eboubaker any progress here? 😄

**Comment by Eboubaker** [comment]
@connorhsm Test and merge

**Review by connorhsm — CHANGES_REQUESTED** [review]
Core function appears to work great, thank you! 

It appears that we've lost some functionality with the search bar. On the current master branch (https://twotech.twohoursonelife.com/) when searhing I can use the up and down keys to select results and Enter to load the page.

This appears broken now with this change, if you could please resolve this before merge.

Please also squash your commits when complete.

**Comment by Eboubaker** [comment]
Good that you've tested. it was indeed not working, it should be fixed now.

**Comment by connorhsm** [comment]
Thank you! ❤️

**Pull request merged**
